Repository AGH-Narzedzia-Informatyczne-2022-2023/druzyna-pierscienia, pull requests merged in 2022-11, with the labels that each got.

#10 import pygame
  move.py
Labels: question

#9 Dodanie glownego szkieletu, podstawowych funkcjonalnosci oraz czesci graficznej menu gry.
  image/menu_background.jpg
  menu.kv
  menu.py
Labels: question

#11 Owoce
  Snake.py
Labels: enhancement

#17 Dodałem nową funkcjonalnośc
  QWERTY.py
  snakeeeeeeee.png
  sniper monkey.jpg
Labels: bug, good first issue
